name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DATE: $(date +%FT%TZ)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: 'master'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"

      - name: Building CSS
        run: |
          npx --package node-sass@latest node-sass --version
          npx --package node-sass@latest node-sass --include-path scss packages/csc/src/scss/common.scss packages/csc/dist/css/common.min.css --output-style compressed

      - name: Building JavaScript

        run: |
          npm i
          npm ci
          npm run js:build

        working-directory: ./packages/csc

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/csc-react

      - name: Building React
        run: |
          npm ci
          npm run build
        working-directory: ./packages/csc-react

      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: react-github-actions-build
          path: build

      - name: Publish CSC
        run: |
          npm ci
          npm publish --access public
        working-directory: ./packages/csc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}

      - name: Publish CSC React
        run: |
          npm ci
          npm publish --access public
        working-directory: ./packages/csc-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}



          
      - name: Commit files # transfer the new html files back into the repository
        run: |
          git config --local user.name "KagariSoft-dev "
          git add .
          git commit -m "🏗️ Files updated" -a
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
